name: Frontend Tests

on:
  push:
    branches: [ main, developtests ]
  pull_request:
    branches: [ main, developtests ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install Angular CLI
        run: npm install -g @angular/cli
      - name: Install dependencies
        run: |
          cd UKParliament.CodeTest.Web/ClientApp
          npm ci
      - name: Run Jasmine/Karma tests
        run: |
          cd UKParliament.CodeTest.Web/ClientApp
          ng test --watch=false --browsers=ChromeHeadless
